- name: Create directory for devserver files
  file:
    path: /var/www/devserver
    state: directory
    mode: '0755'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- git:
    repo: https://github.com/petikehc/solarpi.git
    dest: /var/www/devserver

- lineinfile:
    dest=/home/{{ ansible_ssh_user }}/.bashrc
    line="alias python='/usr/bin/python3'"

- pip:
    requirements=/var/www/devserver/webapp/requirements.txt
    virtualenv=/var/www/devserver/webapp/venv
    virtualenv_python=python3

- lineinfile:
    dest=/home/{{ ansible_ssh_user }}/.bashrc
    line="source /var/www/devserver/webapp/venv/bin/activate"
