- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Ensure Restart=always is in section [Service] in nginx.service
  ini_file:
    path: /lib/systemd/system/nginx.service
    create: no
    section: Service
    option: Restart
    value: always
    mode: '0644'
    no_extra_spaces: yes
    backup: yes

- name: Issue Daemon reload and start the nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes
