- name: Create directory for devserver files
  file:
    path: /var/www/devserver
    state: directory
    mode: '0755'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- git:
    repo: https://github.com/petikehc/solarpi.git
    dest: /var/www/devserver
