- name: Install dependencies for Grafana
  apt:
    name:
      - adduser
      - libfontconfig1
    state: present

- name: Install Grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana-rpi_7.0.0_armhf.deb

- name: Issue daemon-reload and start the Grafana service
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes
