- name: Install packages
  package:
    name:
      - build-essential
      - python-dev
      - python-smbus
      - python3-pip
      - git
      - vim
    state: latest

- pip: name=virtualenv executable=pip3
