- hosts: solarpi
  gather_facts: no
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - include:
        tasks/set_timezone.yml
    - include:
        tasks/update_system.yml
    - include:
        tasks/install_packages.yml
    - include:
        tasks/setup_firewall.yml
    - include:
        tasks/install_influxdb.yml
    - include:
        tasks/install_mosquitto.yml
    - include:
        tasks/install_telegraf.yml
    - include:
        tasks/install_grafana.yml
    - include:
        tasks/enable_i2c.yml
    - include:
        tasks/install_nginx.yml
    - include:
        tasks/install_application.yml
